name: redux_dart_basic_tutorial
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  redux: ^3.0.0
  over_react: '^3.1.0'

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  redux_dev_tools: ^0.4.0

